Import('benv')
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "PATH"


benv.required_thirdparty_libs = \
    rlp_libs

benv.required_libs = \
'''
core.LOG
core.UTIL
'''

benv.cpp_classes = \
'''
PathInfo
StyleBase
PosixStyle
Path
'''

benv.header_files = \
'''
Global.h
'''
