Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "GUI"

benv.required_thirdparty_libs = rlp_libs


benv.required_libs = \
'''
edb.DS
edb.GRAPH
edb.STOR_SQL
edb.CNTRL
'''

benv.required_external_libs = \
'''
core.LOG
core.DS
core.NET
core.CNTRL
gui.BASE
gui.MENU
gui.PANE
gui.GRID
gui.WIDGET
'''

benv.cpp_classes = \
'''
GridView
'''

benv.header_files = \
'''
Global.h
'''

# benv.pybindgen_file = 'py_modulegen.py'