Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "RLANN_MEDIA"


benv.required_thirdparty_libs = rlp_libs

benv.required_external_libs = \
'''
core.LOG
core.PY
core.DS
core.NET
core.CNTRL
revlens.DS
revlens.DISP
revlens.MEDIA
revlens.CNTRL
'''

benv.required_libs = \
'''
extrevlens.RLANN_DS
'''

benv.required_pybindgen_libs = \
'''
'''

benv.cpp_classes = \
'''
DrawNode
Plugin
NodeFactoryPlugin
'''


benv.header_files = \
'''
Global.h
'''


benv.pybind11_info = {
    'classes': {
        'Plugin': {
            'parent': 'MEDIA_Plugin',
            'bootstrap': {
                'bind_object': True
            }
        },
        'NodeFactoryPlugin': {
            'parent': 'DS_NodeFactoryPlugin',
            'bootstrap': {
                'bind_object': True
            }
        }
    }
}