Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "RLANN_DS"


benv.required_thirdparty_libs = rlp_libs

benv.required_external_libs = \
'''
core.LOG
core.PY
core.DS
core.NET
core.CNTRL
revlens.DS
revlens.CNTRL
'''

benv.required_libs = \
'''
'''


benv.cpp_classes = \
'''
BrushBase
PaintBrush
EraserBrush
QImageFrameBuffer
AnnotationEvent
Annotation
AnnotationTask
DrawControllerBase
FrameBuffer
Track
TrackFactoryPlugin
'''


benv.header_files = \
'''
Global.h
'''

benv.pybind11_info = {
    'classes': {
        'Track': {
            'parent': 'DS_Track',
            'holder': 'shared_ptr'
        },
        'Annotation': {},
        'BrushBase': {
        },
        'DrawControllerBase': {
            'parent': 'DS_EventPlugin'
        }
    }
}
