Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "RLQPSD_MEDIA"


benv.required_thirdparty_libs = rlp_libs

benv.required_libs = \
'''
extrevlens.QPSD
'''

benv.required_external_libs = \
'''
core.LOG
revlens.DS
revlens.MEDIA
'''



benv.cpp_classes = \
'''
VideoReader
Plugin
'''

benv.header_files = \
'''
Global.h
'''

# benv.pybindgen_file = 'py_modulegen.py'

