Import("benv")
Import("rlp_libs")

benv.build_type = "shared_library"
benv.lib_name = "DS"


benv.required_thirdparty_libs = \
    rlp_libs

benv.required_libs = \
'''
core.LOG
core.UTIL
core.SEQ
'''

benv.cpp_classes = \
'''
ModelDataItem
FileModelDataItem
'''

benv.header_files = \
'''
Global.h
'''

# benv.pybindgen_file = 'py_modulegen.py'