Import("benv")
Import("rlp_libs")

benv.build_type = "shared_library"
benv.lib_name = "LOG"


benv.required_thirdparty_libs = \
    rlp_libs

benv.cpp_classes = \
'''
Logger
Logging
'''

benv.header_files = \
'''
Global.h
'''

benv.SKIPshiboken_classes = \
'''
Logger
Logging
'''

benv.SKIPrequired_pymodule_libs = \
'''
core.LOG
core.PY
'''