Import('benv')
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "MEDIA"


benv.required_thirdparty_libs = rlp_libs

benv.required_external_libs = \
'''
core.LOG
core.PY
core.SEQ
core.DS
core.NET
core.CNTRL
'''

benv.required_libs = \
'''
revlens.DS
'''

benv.cpp_classes_all = \
'''
ReadEvent
AVInputNode
RetimeNode
DiskCacheNode
Plugin
Factory
'''

benv.cpp_classes = \
'''
ReadEvent
AVInputNode
CompositeNode
Plugin
Factory
'''


benv.header_files = \
'''
Global.h
'''
# benv.pybindgen_file = 'py_modulegen.py'


benv.pybind11_info = {
    'classes': {
        'Plugin': {},
        'Factory': {},
        'CompositeNode': {}
    }
}