
import scaffold.variant
platform_str = scaffold.variant.get_platform()


Import("benv")
Import("buildsys")
Import("rlp_libs")

benv.build_type = "shared_library"
benv.lib_name = "TEST"


benv.required_thirdparty_libs = rlp_libs

benv.required_external_libs = \
'''
core.LOG
'''

benv.required_libs = \
'''
'''

benv.cpp_classes = \
'''
ItemBase
'''


benv.header_files = \
'''
Global.h
'''



# benv.pybindgen_file = 'py_modulegen.py'