Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "RLEXRDS"


benv.required_thirdparty_libs = rlp_libs + \
'''
OpenEXR-3.2.1
'''


benv.required_external_libs = \
'''
core.LOG
core.PY
revlens.DS
'''

benv.required_pybindgen_libs = \
'''
'''

benv.cpp_classes = \
'''
FrameBuffer
'''

benv.header_files = \
'''
Global.h
'''
