Import("benv")
Import("rlp_libs")

benv.build_type = "shared_library"
benv.lib_name = "CNTRL"


benv.required_thirdparty_libs = rlp_libs

benv.required_libs = \
'''
core.LOG
core.CRYPT
core.UTIL
core.NET
core.PY
core.CRYPT
'''

benv.cpp_classes = \
'''
ControllerBase
Auth
'''

benv.header_files = \
'''
Global.h
'''

benv.resource_dir = 'static/certs'

benv.SKIPshiboken_class_prefix = 'CoreCntrl_'
benv.SKIPshiboken_classes = \
'''
Auth
'''

benv.SKIPrequired_pymodule_libs = \
'''
core.CNTRL
core.PY
'''


benv.pybind11_info = {
    'lib_prefix': 'CoreCntrl',
    'classes': {
        'ControllerBase': {

        },
        'Auth': {
            'bootstrap': {
                'bind_object': True
            }
        }
    }
}