Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "GRAPH"


benv.required_thirdparty_libs = rlp_libs

benv.cpp_classes = \
'''
TraverserBase
Node
Parser
'''

benv.required_external_libs = \
'''
core.LOG
'''


benv.required_libs = \
'''
edb.DS
'''

benv.header_files = \
'''
Global.h
'''

# benv.pybindgen_file = 'py_modulegen.py'