Import("benv")
Import("rlp_libs")

benv.build_type = "shared_library"
benv.lib_name = "CRYPT"


benv.required_thirdparty_libs = rlp_libs

benv.required_libs = \
'''
core.LOG
'''

benv.cpp_classes = \
'''
SimpleCrypt
'''

benv.header_files = \
'''
Global.h
'''

