Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "QPSD"


benv.required_thirdparty_libs = rlp_libs


benv.required_external_libs = \
'''
'''

benv.required_pybindgen_libs = \
'''
'''

benv.cpp_classes = \
'''
qpsdhandler
qpsdplugin
'''

benv.header_files = \
'''
Global.h
QPsdPlugin.json
'''


