Import('benv')
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "RLQTMEDIA"


benv.required_thirdparty_libs = rlp_libs

benv.required_external_libs = \
'''
core.LOG
core.PY
core.SEQ
core.DS
core.NET
core.CNTRL
revlens.DS
revlens.MEDIA
'''

benv.required_pybindgen_libs = \
'''
'''

benv.cpp_classes_all = \
'''
VideoReader
Plugin
PyModule
PreviewMakerNode
'''

benv.cpp_classes_1 = \
'''
VideoReader
Plugin
PyModule
'''

benv.cpp_classes = \
'''
Plugin
VideoReader
PreviewMakerNode
'''

benv.header_files = \
'''
Global.h
'''

# benv.pybindgen_file = 'py_modulegen.py'

benv.pybind11_info = {
    'classes': {
        'Plugin': {
            'parent': 'MEDIA_Plugin',
            'bootstrap': {
                'bind_object': True
            }
        },
        'PreviewMakerNode': {
        }
    }
}