import os
import scaffold.variant

Import("benv")
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "UTIL"


benv.required_thirdparty_libs = rlp_libs

benv.required_libs = \
'''
core.LOG
core.CRYPT
core.PY
'''


benv.cpp_classes = \
'''
Convert
Text
Image
AppGlobals
ThreadPool
'''

if os.name == 'nt':
    benv.cpp_classes += \
        '''
        WindowsStacktraceHandler
        '''
else:
    benv.cpp_classes += \
        '''
        StacktraceHandler
        '''


benv.header_files = \
'''
Global.h
'''

benv.SKIPshiboken_classes = \
'''
Text
Image
AppGlobals
'''

benv.SKIPrequired_pymodule_libs = \
'''
core.UTIL
core.PY
'''

benv.pybind11_info = {
    'classes': {
        'Text': {},
        'Image': {},
        'AppGlobals': {}
    }
}
