Import('benv')
Import('rlp_libs')

benv.build_type = "shared_library"
benv.lib_name = "RLQTCNTRL"


benv.required_thirdparty_libs = rlp_libs

benv.required_external_libs = \
'''
core.LOG
core.PY
core.DS
core.NET
core.CNTRL
gui.BASE
gui.MENU
gui.PANE
revlens.DS
revlens.CNTRL
revlens.DISP
'''

benv.required_pybindgen_libs = \
'''
'''

benv.cpp_classes = \
'''
Plugin
'''

benv.header_files = \
'''
Global.h
'''

benv.pybind11_info = {
    'classes': {
        'Plugin': {
            'parent': 'DS_EventPlugin',
            'bootstrap': {
                'bind_object': True
            }
        }
    }
}

# benv.pybindgen_file = 'py_modulegen.py'

